# Generated by Django 5.1 on 2024-08-17 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='LeadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TMType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_factory_num', models.CharField(max_length=60)),
                ('engine_factory_num', models.CharField(max_length=60)),
                ('transmission_factory_num', models.CharField(max_length=60)),
                ('lead_factory_num', models.CharField(max_length=60)),
                ('control_factory_num', models.CharField(max_length=60)),
                ('delivery_agreement_num', models.CharField(max_length=60)),
                ('date_of_shipment', models.DateTimeField(auto_now=True)),
                ('consignee', models.CharField(max_length=60)),
                ('delivery_address', models.CharField(max_length=60)),
                ('equipment', models.CharField(max_length=60)),
                ('client', models.CharField(max_length=60)),
                ('control_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_control_model', to='main.controlmodel')),
                ('engine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_engine_model', to='main.enginemodel')),
                ('lead_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_lead_model', to='main.leadmodel')),
                ('machine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_machine_model', to='main.machinemodel')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_service_company', to='main.servicecompany')),
                ('transmission_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_transmission_model', to='main.transmissionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refusal_date', models.CharField(max_length=60)),
                ('operating_time', models.IntegerField()),
                ('failure_description', models.CharField(max_length=2000)),
                ('spare_parts_used', models.CharField(max_length=2000)),
                ('recovery_date', models.DateTimeField()),
                ('equipment_downtime', models.IntegerField()),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_failure_node', to='main.failurenode')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_machine', to='main.machine')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_recovery_method', to='main.recoverymethod')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_service_company', to='main.servicecompany')),
            ],
        ),
        migrations.CreateModel(
            name='TM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('operating_time', models.IntegerField()),
                ('order_id', models.CharField(max_length=60)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_machine', to='main.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_service_company', to='main.servicecompany')),
                ('tm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tm_type', to='main.tmtype')),
            ],
        ),
    ]
