# Generated by Django 5.1 on 2024-08-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tm_company_tm_producer_alter_complaint_refusal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tm',
            name='company_tm_producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_tm_producer', to='main.servicecompany'),
        ),
    ]
