# Generated by Django 5.1 on 2024-09-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_machine_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='recovery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='refusal_date',
            field=models.DateField(max_length=60),
        ),
        migrations.AlterField(
            model_name='machine',
            name='date_of_shipment',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tm',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tm',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
    ]
