# Generated by Django 5.1 on 2024-09-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_complaint_recovery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='date_of_shipment',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tm',
            name='order_date',
            field=models.DateField(),
        ),
    ]
